### ISSUE TITLE
NRT Slave state transition from Synchronizing to Synchronized

### ISSUE THREAD

**Issue by dev-gb** [modelica/DCPLib#19]
I have set up a DcpSlave in NRT Operating Mode and had troubles switching from  SYNCHRONIZING to SYNCHRONIZED. All callbacks are synchronous.

As far as i understand, this transition should be issued automatically by the DcpSlave. Like the transition from preparing to prepared. Unfortenately this does not work in NRT Mode. 
The transition from preparing to prepared starts automatically.

Do i need to trigger the state transition SYNCHRONIZING to SYNCHRONIZED by myself?

**Comment by clemensschiffer** [comment]
Yes, the slave should transition to SYNCHRONIZED on its own(since it is SIG_SYNCHRONIZED ).
The DcpManagerSlave doesn't do this on its own. (Should we implement this? )

Anyway in NRT in any state of superstate run a do_step can be performed triggering one computation,
so we can do the steps in synchronizing. 
But computation is meant to  be done in RUNNING.(?)

Dont forget to set the NRT Callback:
        manager->setSynchronizingNRTStepCallback<SYNC>(std::bind(&Slave::doStep, this, std::placeholders::_1));

lg
C

**Comment by dev-gb** [comment]
would be better if this is handled directly by the dcpManagerSlave.

could be that most of the master implementations would await the synchronized slave transmission to start the simulation.

**Comment by clemensschiffer** [comment]
yes i agree

**Comment by ChKater** [comment]
This was a bug in the library. The library takes care of all state changes. This is fixed now.
